---
apiVersion: machineconfiguration.openshift.io/v1
kind: MachineConfigPool
metadata:
  name: example-mcp
  labels:
    machineconfiguration.openshift.io/role: example
spec:
  machineConfigSelector:
    matchExpressions: []
    #- key: machineconfiguration.openshift.io/role
    #  operator: In
    #  values: [ worker, example ]
  paused: false
  maxUnavailable: 1
  nodeSelector:
    matchLabels: {}
    #  node-role.kubernetes.io/example: ""
